//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet_3._0.Vistas.V_Comunicacion {
    
    public partial class V_Control_Aplicativos {
        
        protected global::System.Web.UI.UpdatePanel pnlAplicativos;
        
        protected global::System.Web.UI.WebControls.Literal ltr_mensaje;
        
        protected global::System.Web.UI.WebControls.LinkButton btn_modal_crear;
        
        protected global::System.Web.UI.WebControls.LinkButton btn_modal_actualizar;
        
        protected global::System.Web.UI.WebControls.LinkButton btn_modal_eliminar;
        
        protected global::System.Web.UI.WebControls.TextBox txt_buscar;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tbl_aplicativos;
        
        protected global::System.Web.UI.WebControls.HiddenField hf_id_aplicativo;
        
        protected global::System.Web.UI.WebControls.HiddenField hf_imagen_actual;
        
        protected global::System.Web.UI.WebControls.TextBox txt_titulo;
        
        protected global::System.Web.UI.WebControls.TextBox txt_descripcion;
        
        protected global::System.Web.UI.WebControls.TextBox txt_url;
        
        protected global::System.Web.UI.WebControls.FileUpload fud_imagen;
        
        protected global::System.Web.UI.WebControls.DropDownList ddl_seccion;
        
        protected global::System.Web.UI.WebControls.LinkButton lnk_crear_aplicativo;
        
        protected global::System.Web.UI.WebControls.TextBox txt_titulo_edit;
        
        protected global::System.Web.UI.WebControls.TextBox txt_descripcion_edit;
        
        protected global::System.Web.UI.WebControls.TextBox txt_url_edit;
        
        protected global::System.Web.UI.WebControls.FileUpload fud_imagen_edit;
        
        protected global::System.Web.UI.WebControls.DropDownList ddl_seccion_edit;
        
        protected global::System.Web.UI.WebControls.DropDownList ddl_estado;
        
        protected global::System.Web.UI.WebControls.LinkButton lnk_actualizar_aplicativo;
        
        protected global::System.Web.UI.WebControls.LinkButton lnk_eliminar_aplicativo;
    }
}
