//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet_3._0.Vistas.V_Gestion_Humana
{


    public partial class V_Evaluacion_Desempeño
    {
    }
}
