//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet_3._0.Vistas.V_Perfil {
    
    public partial class V_Aplicativos {
        
        protected global::System.Web.UI.WebControls.PlaceHolder phEmpresarialesVacio;
        
        protected global::System.Web.UI.WebControls.Repeater rptEmpresariales;
        
        protected global::System.Web.UI.WebControls.PlaceHolder phConsultaVacio;
        
        protected global::System.Web.UI.WebControls.Repeater rptConsulta;
        
        protected global::System.Web.UI.WebControls.PlaceHolder phSoporteVacio;
        
        protected global::System.Web.UI.WebControls.Repeater rptSoporte;
    }
}
